[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.9" # Solana version to use

[features]
seeds = true

[registry]
url = "https://api.apr.dev"

[workspace]
members = [
    "programs/merkle-distributor",
]

[provider]
cluster = "testnet"
wallet = "payxNNNpXxeZMuqCPoiDxCvPRKamjq3mzdiTxHZxUhq.json"

[programs.mainnet]
merkle_distributor = "ADis3cccJHS6dmj8MPCG1NGGuXBN2ZSaaXFwKKU7UUgF"

[programs.devnet]
merkle_distributor = "ADis3cccJHS6dmj8MPCG1NGGuXBN2ZSaaXFwKKU7UUgF"

[programs.testnet]
merkle_distributor = "ADis3cccJHS6dmj8MPCG1NGGuXBN2ZSaaXFwKKU7UUgF"

[programs.localnet]
merkle_distributor = "ADis3cccJHS6dmj8MPCG1NGGuXBN2ZSaaXFwKKU7UUgF"

[scripts]
test = "yarn mocha"
